gpu_set_ztestenable(1)
gpu_set_zwriteenable(1)
gpu_set_texrepeat(1)
vertex_format_begin()
vertex_format_add_position_3d()
vertex_format_add_normal()
vertex_format_add_texcoord()
vertex_format_add_color()
vertex_format = vertex_format_end()
depths = 0
model = load_obj("treasuredoor.obj", "treasuredoor.mtl", self)
